# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#		1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?
import sys

def generate_triangle_numbers(n):
	triangles = []
	for i in range(n + 1):
		triangles.append(int(n * (n+1) / 2))
	return triangles

def factors(n):
	factors = []
	for i in range(1, n + 1):
		if n % i == 0:
			factors.append(i)
	return factors

triangles = generate_triangle_numbers(10000)
for triangle in triangles:
	if len(factors(triangle)) > 500:
		print(triangle)
		sys.exit(0)